# Generated by Django 4.1.3 on 2022-11-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_time_bid_posted_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='posted_on',
            new_name='time',
        ),
    ]
