# Generated by Django 4.1.3 on 2022-11-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='won',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='auctions.listing'),
        ),
    ]
